baseURL: https://gmbernardoharrington.netlify.app/
theme: hugo-apero
languageCode: en
title: Gabriel Mateus Bernardo Harrington
author: Mateus Harrington
copyright: '&copy; Gabriel Mateus Bernardo Harrington <script>document.write( new Date().getFullYear() );</script>'
googleAnalytics: 'UA-171428188-1'
disqusShortname: ''
metaDataFormat: yaml
footnoteReturnLinkContents: '&#8617;'
paginate: 5
preserveTaxonomyNames: yes
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
enableEmoji: yes
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      hardwraps: no
      unsafe: yes
  highlight:
    style: github
  tableOfContents:
    endLevel: 2
    ordered: no
    startLevel: 2
params:
  custom_theme: ''
  # embeded font options: Fraunces, Commissioner
  # EB Garamond, Alegreya Sans
  # Bitter, Metropolis
  customheadingFontFamily: Fraunces
  customtextFontFamily: Metropolis
  description: Gabriel Mateus Bernardo Harrington's personal website/portfolio/blog
  favicon: /img/icon.png
  headingFontFamily: sans-serif
  logo: /img/icon.png
  mainSections:
    - blog
    - publications
    - talk
  math:
    renderer: katex
  navallcaps: yes
  orgLocal: Cardiff
  orgName: Cardiff University
  sharing_image: /img/icon.png
  social:
    - icon: github
      icon_pack: fab
      url: https://github.com/H-Mateus
    # - icon: facebook-square
    #   icon_pack: fab
    #   url: https://www.facebook.com/hashtag/ap%C3%A9ro
    # - icon: instagram
    #   icon_pack: fab
    #   url: https://www.instagram.com/explore/tags/apero/
    # - icon: impactstory
    #   icon_pack: ai
    #   url: https://impactstory.org/u/0000-0002-8082-1890
    - icon: twitter
      icon_pack: fab
      url: https://twitter.com/Hmateus4
    - icon: google-scholar
      icon_pack: ai
      url: https://scholar.google.co.uk/citations?user=FB3HdaYAAAAJ&hl=en
    - icon: orcid
      icon_pack: ai
      url: https://orcid.org/0000-0001-6075-3619
    - icon: rss
      icon_pack: fas
      url: /blog/index.xml
  socialInFooter: yes
  socialInHeader: no
  textFontFamily: sans-serif
  # use a built-in color theme
  # one of: forest / grayscale / peach / plum /
  #         poppy / sky / violet / water
  theme: sky
  twitter: Hmateus4
  utterances:
    issue_term: pathname
    label: 'comments :crystal_ball:'
    repo_name: H-Mateus/personal_website
    theme: boxy-light
    use_utterances: yes
taxonomies:
  category: categories
  series: series
  tag: tags
menu:
  footer:
    - name: License
      title: License
      url: /license/
      weight: 1
    - name: Contact
      title: Contact form
      url: /contact/
      weight: 2
    # - name: Contributors
    #   title: Contributors
    #   url: /contributors/
    #   weight: 3
  header:
    - name: About
      title: About Blogophonic
      url: /about/
      weight: 1
    - name: Blog
      title: Blog
      url: /blog/
      weight: 2
    - name: Publications
      title: Publications
      url: /publications/
      weight: 2
    # - name: Projects
    #   title: Project Portfolio
    #   url: /project/
    #   weight: 3
    - name: Talks
      title: Talks
      url: /talk/
      weight: 4
    - name: Teaching
      title: Teaching
      url: /teaching/
      weight: 5
    # - name: A collection
    #   title: A collection
    #   url: /collection/
    #   weight: 5
    # - name: Elements
    #   title: Element Page
    #   url: /elements/
    #   weight: 6
privacy:
  disqus:
    disable: no
  googleAnalytics:
    anonymizeIP: yes
    disable: no
    respectDoNotTrack: yes
  instagram:
    disable: no
    simple: yes
  twitter:
    disable: no
    enableDNT: yes
    simple: no
  vimeo:
    disable: no
    enableDNT: yes
    simple: yes
  youtube:
    disable: no
    privacyEnhanced: yes

