---
title: My PhD journey
date: '2022-08-13'
categories:
  - Academia
subtitle: ''
description: ''
date-modified: '2022-08-13'
draft: true
---

# Beginning: nervous excitement

So in the UK PhDs are typically 3 year affairs (with an extra unfunded 4$^{th}$ for writing up if you need it), but mine was a little different.
My PhD was part of the [Centre for Doctoral Training](link-here), which is effectively where the research councils (the [MRC](link-here) and [EPSRC](link-here) in this case) decide on a area they'd like to advance, and set up a group of three institutions to host a series of PhDs (~12 per year) focused on that area.
So in my case, these were the universities of [Loughborough](link-here), [Nottingham](link-here) and [Keele](link-here), and our topic was regenerative medicine (basically lots of stem cell stuff).

The main difference here is an extra initial year, where we did a few group activities, but main do a mini-project at each of the three centres, before getting to choose our actual PhD project at one of the centres.
It's an interesting set up, and as someone who was more than a little terrified at the notion of committing to a project for 3 years, especially without knowing much about who I'd be working with, I greatly appreciated the chance to get to know the labs I might work in prior to accepting a project.
Getting exposure to three institutes is a good networking exercise as well, so overall I'd rate the CDT experience reasonably highly.



