---
title: "Supporting Statement - reference: 11110BR"
author: "Gabriel Mateus Bernardo Harrington"
date: "`r Sys.Date()`"
output:
  word_document:
    toc: no
  pdf_document:
    toc: no
  html_document:
    highlight: tango
    number_sections: yes
    theme: united
    toc: yes
    toc_float:
      collapsed: yes
    code_download: yes
    df_print: paged
bibliography: /home/mateus/Documents/masterLib.bib
csl: /home/mateus/Documents/citation_styles/elsevier-vancouver.csl
link-citations: yes
---

```{r, label='setup-options', include=FALSE}
knitr::opts_chunk$set(
  eval = TRUE, # eval code chunks
  echo = TRUE, # include source code
  #fig.width = 6, # set figure dims
  #fig.height = 6
  warning = FALSE, # exclude warnings
  message = FALSE, # exclude messages
  error = FALSE # exclude errors
)
```

The IPSC Platform to Model Alzheimer's Disease Risk project represents an outstanding opportunity for valuable progress to be made understanding this devastating disease.
It is also an opportunity for me to not just apply, but develop and refine my research skill set.
I am an ideal candidate and enthusiastic researcher, so I hope you will consider me for the Research Associate position.

I have outlined below how I meet the essential and desirable job criteria.

*1.    Postgraduate degree at PhD level (or nearing completion / submission) in a related subject area or relevant industrial experience*

Currently, I am a final-year PhD student at Keele University's Spinal Studies group, based in [The Robert Jones and Agnes Hunt Orthopaedic Hospital](https://www.rjah.nhs.uk/), and will submit my thesis entitled 'Exploring the serum proteome of spinal cord injured patients: Identifying prognostic biomarkers and new treatment targets' by September 20$^{th}$ 2021.
My project centres on prognostic modelling of spinal cord injury (SCI), a life changing trauma that lacks any definitive treatment.
Recovery of neurological function following SCI is highly variable, with some regaining near full motor and sensory function, and others little or no substantial recovery.
This uncertainty is often psychologically difficult for patients to accept the extent of their injury and comply with their clinical care team.
The unpredictable recovery also makes adequately powering a clinical trail of new therapies extremely challenging, thus stymieing their development.

*2.    An established expertise and proven portfolio of research and/or relevant industrial experience within the following research fields:*
  *- Association studies for complex disease*
  *- Big Data*

My PhD has allowed me to develop substantial research experience, particularly in bioinformatics analysis.
My first published article involved modelling neurological outcomes of spinal cord injury with retrospective patient data from 500 patients.
This dataset was longitudinal, covering the admission period post-injury, and included dozens of clinical variables from basic demographic information, age and injury, sex, etc., and other aspects of care given from medications, surgical procedures and all haematological tests conducted during care.
This allowed me to develop my bioinformatic skills, initially with [R](https://www.r-project.org/) to prepare the data for analysis, and later with Linux and Bash scripting skills when extensive bootstrapping for model validation demanded the use of University's super computer.

Subsequently I worked on proteomic experiments utilising patient plasma samples.
Once again this provided an opportunity to develop my bioinformatic skills, particularly with Bash and the HPC as the >10Gb size of each of the 24 faction files made analysis on typical consumer hardware impractical.
Whilst my group has traditionally relied on the software provided by the vendor of the mass spectrometer used to run the samples for analysis of this type of experiment, I sought to develop a pipeline myself, both to develope my skills and to gain greater transparency and reproducibility in my work.

3.    Knowledge of current status of research in specialist field

As part of my PhD project I have developed a suite of bioinformatic skill and gained a deep appreciation for the challenges associated with translating scientific research to clinical application, or the so called "bench to bedside" pathway, including the valuable input clinicians can offer to this process, and to research more broadly, which many groups lack good access to.
This has included applications to ethics boards, adherence to good clinical practice, consenting patients to participate in research, and handling of samples under the jurisdiction of the human tissue act.

*4.    Proven ability to publish in national journals and/or other research outputs*

The aforementioned modelling of retrospective patient data was published with myself as first author in 2020.[@bernardo_harrington_routinely_2020]
Preceding this work was a preliminary study for which I am second author.[@brown_preliminary_2019]
Through both of these papers I identified a link between markers of liver function and neurological outcomes of SCI.
I am currently drafting two first author publications from my PhD project, firstly the aforementioned proteomic experiments, and another using external datasets to validate my initial retrospective patient modelling.

5.    Knowledge and understanding of competitive research funding to be able to develop applications to funding bodies

I applied for and was awarded a £4,000 consumable grant to undertake metabolomic experiments from the Centre for Doctoral Training this year.
We hope to carry out the experiments this summer, though COVID-19 may cause delays.
Previously I was awarded a travel grant from the Keele Postgraduate Research Committee to attend [ISCoS 2020](https://www.iscosmeetings2020.org/) which was originally due to be held in Japan, but was changed to a virtual meetings owing to COVID-19.

*6.    Proven ability in effective and persuasive communication*

During a conversion at the first major conference of my PhD project surrounding reproducible research, a topic near and dear to me, the conference organisers were impressed with my passion and knowledge of the topic and so invited to me to give a talk on the topic during the next years Centre for Doctoral Training.
Since giving the talk I have had several audience members reach out to me for guidance in establishing more reproducible workflows in their respective labs.
This had provided a good opportunity to further develop my communication and teaching abilities as I have had to accommodate individuals and groups of varying computational experience.

*7.    Ability to supervise the work of others to focus team efforts and motivate individuals*

During my PhD our group has hosted several undergraduate students for their sandwich years, many of which I supervised.
I quickly realised the importance of facilitating the professional development of the supervisee to stoke motivation, and so endeavoured to focus my guidance on data analysis and other bioinformatic skills where my skill are strongest in our group, allowing my colleagues more experienced in wet lab work to provide guidance in that domain.
This division of teaching allowed our group to provide more focused guidance to our students for which they provided very positive feedback.

*8.    Proven ability to demonstrate creativity, innovation and team-working within work*

My commitment to reproducibility has allowed to be build two pipelines in collaboration with clinicians at our Trust.
One a complete proteomic analysis pipeline, and the other for tidying and modelling of our patient data.
Several of my colleagues are currently using these pipelines in their own projects and they have found they excellent facilitators or their research that allow them to spend more time focusing on designing and executing their experiments without have to reinvent the wheel each time when it comes to data processing.
We expect this to directly lead to a higher throughput of quality publications at our lab.

*9.    Proven ability to work without close supervision*

The COVID-19 pandemic has presented many challenges during my PhD.
One of the most important skills that benefited me during this time has been my high degree of self-motivation and ability to continuate to work productively, including the discipline required to work well from home, with heavily reduced supervision.

*10.    Relevant professional qualification(s)*

In 2010 I completed the [Duke of Edinburgh's](https://www.dofe.org/) silver award, which helped me develop self-confidence, leadership, initiative, drive, teamwork and communication skills.
I am also proficient in Portuguese and have spend significant time in Portugal, Brazil and Angola.

*11.    Evidence of collaborations with industry.*

During my time at the [Bionics Institute](https://www.bionicsinstitute.org/) we worked closely with several industry and academic collaborators.
I learnt that whilst there is the great deal of overlap in the approaches of industry and academic, there are certainly differences.
A greater emphasis on cost-effectiveness from the earliest stages of research, and in particular ensuring appropriate consideration has been paid to intellectual property during research.

*12.     Proven ability to adapt to the changing requirements of the Higher Education community.*

In the first year of my PhD I had the opportunity to do mini-projects at several institutions.
This has allowed to have hands-on experience and laboratories in at Lancaster University, Keele University, Nottingham University and Loughborough University.
I have also engaged in outreach activities, including booth presentations at science fairs and career guidance at local schools.
In addition to fellow PhD students, I worked alongside undergraduate students, postdoctoral researchers, tenured staff and research assistants.
This have given me exposure to wide range of perspectives and concerns felt by all members of the Higher Education community, as well of the perspective of students and their parents in earlier education.

*13.    Evidence of ability to participate in and develop both internal and external networks and utilise them to enhance the research activities of the School.*

I strongly believe collaboration is a crucial cornerstone of quality research.
As such I have continually reached out to experts from our institutions to establish collaborative links.
More specifically, whilst building my proteomic data analysis pipeline I reached out to several proteomic bioinformaticians to ensure I was following best practises in my design.
I also established collaborative links with[Dr. Brian Kwon](http://icord.org/researchers/dr-brian-kwon/) and [Prof. Dana McTigue](https://scholar.google.co.uk/citations?hl=en&user=L5pmlf4AAAAJ&view_op=list_works&sortby=pubdate), experts in SCI biomarkers and the liver-SCI axis respectively, which we are actively working on currently.

This project would allow me to further develop my skill as a researcher and give me strong standing to attract further external funding to grow my academic career.
Thank you for your time and consideration.
I look forward to the opportunity to discuss the project further.

Kind regards,
Gabriel Mateus Bernardo Harrington

# References
